version: '3.8'

services:
  postgres:
      image: postgres:13
      container_name: postgres_container
      volumes:
        - postgres_data:/var/lib/postgresql/data
      env_file: ../.env
      ports:
        - "5432:5432"

  pgadmin:
      image: dpage/pgadmin4
      container_name: my_pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "8080:80"

volumes:
  postgres_data:

