GAME_CONSTANTS = {
    'MIN_DIR': 0.5,
    'VELOCITY': 1000,
    'FACTOR': 1.5,
    'WIN_SCORE': 10,
    'PADDLE_SPEED': 800,
    'PADDLE_HEIGHT': 280,
    'BALL_RADIUS': 60,
    'COURT_HEIGHT': 785,
    'COURT_WIDTH': 1600,
    'FRAME_TIME': 0.016
}

TOURNAMENT_CONFIG = {
    'PLAYERS_PER_TOURNAMENT': 4,
    'WAITING_TIMEOUT': 300,
    'MATCH_TIMEOUT': 600
}